function [x_grid,t_grid,u_array,v_array,U_array,V_array] = solver_wrapper_ard( ...
    u0_fun,v0_fun,f_fun,dx,dt,L,T,...
    c,gamma,nu,...
    bcType,q,r,space_order)

    if nargin < 14
        space_order = 2;
    end

    [x_grid,~,~,t_grid,u_array,~,~,UL_array,UR_array] = ard_solver( ...
        u0_fun,v0_fun,f_fun,...
        dx,dt,L,T,...
        c,gamma,nu,...
        bcType,q,r,space_order);
    
    % Compute true global modal coefficients
    U_array = dct(u_array); 
    v_array = zeros(size(u_array));
    V_array = zeros(size(u_array)); % Not tracking v_array dynamically in this wrapper
end
